export const projects = [
  {
    id: 1,
    title: "Social Media App",
    images: [
      "/images/social-home",
      "/images/social-newsfeed",
      "/images/social-register",
    ],
    desc: "Developed a social media web app in Next.js and Express.js with MongoDB. This app is similar to twitter where you can follow, unfollow and share your posts with your follower and the followers can also comment and like your post.The main challenge was to make it realtime so I used Socket.io to make it possible.I have used and amazing UI library called Ant design for most of the sections.",
    tech: [
      "React",
      "Next",
      "Ant Design",
      "Context API",
      " Socket.io",
      "Express",
      "MongoDB",
      "Javascript ES6",
      "CSS3 – CSS Modules",
      "HTML5 ",
    ],
  },
  {
    id: 2,
    title: "Youtube Clone",
    images: [
      "/images/youtube-splash",
      "/images/youtube-home",
      "/images/youtube-signin",
      "/images/youtube-googleauth",
    ],
    desc: "YouTube clone developed with MERN stack where users can upload their videos and watch the videos uploaded by other users. Users can also like, comment and subscribe the other user and watch the latest videos.I have used firebase storage to store the videos and also provided google authentication for Google users to log in through their google accounts directly.",
    tech: [
      "React",
      "TailwindCSS",
      "Redux",
      "Express",
      "MongoDB",
      "Javascript ES6",
      "CSS3 – CSS Modules",
      "HTML5 ",
    ],
  },
  {
    id: 2,
    title: "Khayal Management",
    images: [
      "/images/hero",
      "/images/challenges",
      "/images/reviews",
      "/images/satisfaction",
    ],
    desc: "This is a corporate website for an NGO which I developed with JAM stack. I have used STRAPI as a headless cms and NEXT.js for the front end.GraphQL is used in this project to query the Data and Cloudinary for media management.",
    tech: [
      "Next.js",
      "Strapi",
      "React Bootstrap",
      "Cloudinary",
      "PostgresSQL",
      "Javascript ES6",
      "CSS3 – CSS Modules",
      "HTML5 ",
    ],
  },
];
